### ISSUE TITLE
verifyPhoneNumber works?

### ISSUE THREAD

**Issue by christoribeiro** [chemerisuk/cordova-plugin-firebase-authentication#1]
Hello @chemerisuk,

Do `verifyPhoneNumber` and `signInWithVerificationId` work? 
Do you plan to add this plugin into the ionic-native list?

**Comment by chemerisuk** [comment]
They should work yes. I will document those methods and release the next plugin version soon.

**Comment by christoribeiro** [comment]
I fetch your version with `ionic cordova plugin add https://github.com/...` but I don't know how to use it as it's not a ionic-native plugin :/
