### ISSUE TITLE
How to add custom scope on google sign in?

### ISSUE THREAD

**Issue by stefdelec** [chemerisuk/cordova-plugin-firebase-authentication#102]
Hi,
Thanks for this plugin. I was wondering how to add scope to authentification with google like in 
https://firebase.google.com/docs/reference/js/firebase.auth.OAuthProvider

`
// Start a sign in process for an unauthenticated user.
var provider = new firebase.auth.OAuthProvider('google.com');
provider.addScope('profile');
provider.addScope('email');
firebase.auth().signInWithRedirect(provider);
`

**Comment by chemerisuk** [comment]
Use https://github.com/EddyVerbruggen/cordova-plugin-googleplus and specify appropriate value for `scopes` option.
