### ISSUE TITLE
Returning Cant find plugins of undefined

### ISSUE THREAD

**Issue by mashrurbd** [chemerisuk/cordova-plugin-firebase-authentication#103]
window.cordova.plugins.firebase.auth.verifyPhoneNumber  method returning " type error: Cant find plugins of undefined" how to fix it?

**Comment by mashrurbd** [comment]
@chemerisuk can you please help me to find a solution?

**Comment by alpeshvasani** [comment]
@mashrurbd Did you found the solution? I facing the same.
