### ISSUE TITLE
Plugin doesn't support this project's cordova-android version. cordova-android: 9.0.0

### ISSUE THREAD

**Issue by tanhatariq** [chemerisuk/cordova-plugin-firebase-authentication#108]
# I have cordova 10.0.0 installed and when i add this plugin, i get this error, trying to add Phone Authentication in our App

*Plugin doesn't support this project's cordova-android version. cordova-android: 9.0.0, failed version requirement: <9.0.0
Skipping 'cordova-support-google-services' for android*

![image](https://user-images.githubusercontent.com/6288495/96506897-0a1c4d80-1276-11eb-8485-335686336531.png)

**Comment by chemerisuk** [comment]
@tanhatariq this is ok.

**Comment by tanhatariq** [comment]
> @tanhatariq this is ok.

But @chemerisuk it fails on *cordova build* or *cordova run* and when i remove plugin, build succeeds

**Comment by chemerisuk** [comment]
This is just a warning, not a complication error.

**Comment by tanhatariq** [comment]
@chemerisuk but build fails after adding this plugin, and when i remove plugin build succeeds.. i am not able to compile after i add this plugin..

**Comment by chemerisuk** [comment]
@tanhatariq can you post build log?

**Comment by tanhatariq** [comment]
@chemerisuk sure i am posting in a while

**Comment by tanhatariq** [comment]
![image](https://user-images.githubusercontent.com/6288495/96517254-4061c900-1286-11eb-9a07-e9a4f750f235.png)

**Comment by chemerisuk** [comment]
@tanhatariq you have other cordova plugin that relies on gradle plugin for google services and doesn't implement it properly. Please contact a plugin author and send him a link https://cordova.apache.org/announcements/2020/06/29/cordova-android-9.0.0.html. Section **Added Google Services Support**.
