### ISSUE TITLE
Handle incoming SMS auto verification in android

### ISSUE THREAD

**Issue by bengchet** [chemerisuk/cordova-plugin-firebase-authentication#11]
Hi,

First of all, thanks for this plugin. I have implemented this plugin in my Ionic Project for a while. 

In Android, I was facing an issue that I occasionally get a message "The SMS code has expired" after I have entered SMS OTPcode and hit verify button. At that time I have already the verification code and everything else to proceed. It turns out the plugin has skipped one callback to handle incoming SMS auto verification. Please check this [Auto-retrieval](https://firebase.google.com/docs/auth/android/phone-auth#verification-callbacks)

If SMS auto retrieval is implemented, it will trigger action in **onVerificationCompleted** automatically. So when SMS arrives and user try to enter SMS OTP code to proceed with **cordova.plugins.firebase.auth.signInWithVerificationId**, at that time the error message will be shown that SMS code has expired. In fact verification has already been done when SMS has arrived.

Therefore I modified the source code (android) to handle this situation. I added a new function **waitForSMSVerificationResult**  to register the callback to onVerificationCompleted. General code will be as below.

```
// after user wants to get OTP code
cordova.plugins.firebase.auth.waitForSMSVerificationResult(function(userInfo){
    // get user info after sign in successfully
    console.log(userInfo)
    // perform action after user sign in
});

cordova.plugins.firebase.auth.verifyPhoneNumber(phone, 0, function(verificationId) {
   if(verificationId) {
     // store verification somewhere else 
   }
});

// after user enters SMS OTP code
cordova.plugins.firebase.auth.signInWithVerificationId(verificationId, SMScode);

```
Above is just temporary modification, hope you can restructure the code for handling SMS auto-retrieval situation.

For IOS I didn't get any trouble on this. It always prompts user to enter SMS OTP code to proceed with phone verification, no instant or SMS autoretrieval verification.

Again thanks for this plugin.

**Comment by bengchet** [comment]
Here is my forked repo [https://github.com/bengchet/cordova-plugin-firebase-authentication](https://github.com/bengchet/cordova-plugin-firebase-authentication)

**Comment by chemerisuk** [comment]
@bengchet you can handle auto-retrieval case by checking `verificationId `:

```js
cordova.plugins.firebase.auth.verifyPhoneNumber(phone).then(function(verificationId) {
   if(verificationId) {
      // pass to signInWithVerificationId
   } else {
      // auto verified
   }
});
```

Check https://github.com/chemerisuk/cordova-plugin-firebase-authentication/blob/master/src/android/FirebaseAuthenticationPlugin.java#L159 and use the latest version of the plugin.

**Comment by bengchet** [comment]
Hi,

For what I have tested, SMS auto retrieval still gives verificationId in advance, which gives me false alarm that I need to signInWithVerificationId. Instant verification will not give verificationId.

Can help verify this?

Thanks.

**Comment by chemerisuk** [comment]
@bengchet hm, it seems like `onVerificationCompleted` is called after `onCodeSent` in that case. Can you check when `onCodeAutoRetrievalTimeOut` called in such flow? I intentionally always set auto retrieval timeout to 0 in order to disabled that logic (temporary).

Proper handling of auto verify on Android definitely requires some extra work and planned.

**Comment by chemerisuk** [comment]
Take a look at https://github.com/chemerisuk/cordova-plugin-firebase-authentication/commit/8ec2d27f852d39ffb7a89bd543ed9ab1475c4843. It introduces changes that I believe can help to solve the issue. The main change is that `successCallback` for method `verifyPhoneNumber` can be called several times on Android: with string `verificationId` or with object `userInfo`. To distinct those values you can just use operator `typeof`:

```js
auth.verifyPhoneNumber(phoneNumber).then((verificationId) => {
    if (verificationId && typeof verificationId === "string") {
        const smsCode = prompt("Enter SMS verification code");

        return auth.signInWithVerificationId(verificationId, smsCode);
    }

    return verificationId;
}).then((userInfo) => {
    if (userInfo) {
        // user signed in
    }
});
```
Let me know if changes work for you (get the plugin code for master).

**Comment by bengchet** [comment]
Hi,

I assume prompt is async function that waits for user input for SMS code? If user enters SMS code, it will return a promise `signInWithVerificationId`? If verificationId is not a string, it returns a promise that waits for signincallback?

If that is the case, in my opinion this solution still doesn't solve initial problem. **SMS auto retrieval will still give verificationId in advance**, which in turns prompt user for SMS code according to logic above. When SMS arrives, verification is already being done while prompting for SMS code from user. Correct me if I am wrong.

Anyway, the code now is shorter and more organised. Good job!

**Comment by chemerisuk** [comment]
After all I decided to be consistent with Firebase Web APIs and implement support for [onAuthStateChanged callback](https://github.com/chemerisuk/cordova-plugin-firebase-authentication/commit/f79d348d47a10c8df9cf366ea24407c7f0225017#diff-84de9215166cd80ad7d622bf90ddd259R40).

> This method gets invoked in the UI thread on changes in the authentication state:
Right after the listener has been registered
When a user is signed in
When the current user is signed out
When the current user changes

So for the phone number case the callback should trigger on auto retrieval or instant verification.

**Comment by bengchet** [comment]
Hi,

Yes nice! I will give it a try and let you know the result.

**Comment by chemerisuk** [comment]
Works on my side, please reopen the issue if it exists in v0.13.2
