### ISSUE TITLE
Android build app (APK) closing on Phone Auth function: verifyPhoneNumber(phone,timeout)

### ISSUE THREAD

**Issue by SparshaDhar** [chemerisuk/cordova-plugin-firebase-authentication#112]
Hi,
While on version 3.6.0 Phone Auth is working perfectly, whenever using the latest plugin version 4.1.0 the apk build closes automatically (stops working) everytime on calling `cordova.plugins.firebase.auth.verifyPhoneNumber(phone, timeout)`
My cordova android version is `android@8.1`.
Can this be fixed? Thankyou so much.

[logs.txt](https://github.com/chemerisuk/cordova-plugin-firebase-authentication/files/5642646/logs.txt)

**Comment by chemerisuk** [comment]
@SparshaDhar logcat output could help to understand source of the problem.

**Comment by SparshaDhar** [comment]
@chemerisuk Thanks for the quick reply, I tried to filter out the logs (I'm new to cordova). I attached the file: [logs.txt](https://github.com/chemerisuk/cordova-plugin-firebase-authentication/files/5642646/logs.txt)
Its huge!
Hope this helps

**Comment by chemerisuk** [comment]
@SparshaDhar same problem here https://github.com/firebase/firebase-android-sdk/issues/2164. It looks like the problem should be fixed by Google Firebase team. For now you could add

    implementation "androidx.browser:browser:1.2.0"

to app/build.gradle to solve the issue.
