### ISSUE TITLE
IOS_FIREBASE_POD_VERSION in the plugin

### ISSUE THREAD

**Issue by deliverymanager** [chemerisuk/cordova-plugin-firebase-authentication#125]
@chemerisuk Hello. Is it in your plans to add a IOS_FIREBASE_POD_VERSION in order to be able to select the version of the pod as you did for the analytics plugin?
Right now the authentication uses 8.2.0 by default and the analytics plugin the 8.8.0 version.

**Comment by chemerisuk** [comment]
Thanks @deliverymanager, it's in my TODO list. Planning to publish update at this weekend

**Comment by chemerisuk** [comment]
Published in v5.1.0
