### ISSUE TITLE
Unable to build in iOS using XCode 13.1

### ISSUE THREAD

**Issue by supportreq** [chemerisuk/cordova-plugin-firebase-authentication#126]
While trying to compile Ionic app using capacitor I am getting the following error:

(project-root-path)/ios/capacitor-cordova-ios-plugins/sources/CordovaPluginFirebaseAuthentication/FirebaseAuthenticationPlugin.h:3:9: Include of non-modular header inside framework module 'CordovaPlugins.FirebaseAuthenticationPlugin': '(project-root-path)/ios/App/Pods/Headers/Public/Firebase/Firebase.h'
 
Could not build Objective-C module 'CordovaPlugins'
---
I have used the following versions in a new ionic project:
npm install cordova-plugin-firebase-authentication@4.0.2
npm install @ionic-native/firebase-authentication@5.36.0
npm install firebase@8.10.0

=> project info
Ionic:
   Ionic CLI                     : 6.11.12 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 6.0.0
   @angular-devkit/build-angular : 13.0.4
   @angular-devkit/schematics    : 13.0.4
   @angular/cli                  : 13.0.4
   @ionic/angular-toolkit        : 5.0.3

Utility:

   cordova-res (update available: 0.15.4) : 0.15.1
   native-run                             : 1.5.0

System:

   NodeJS : v14.17.5 (/usr/local/bin/node)
   npm    : 7.21.0
   OS     : macOS Big Sur

=> capacitor info
   "@capacitor/app": "^1.0.7",
   "@capacitor/core": "^3.3.3",
   "@capacitor/ios": "^3.3.3",
   "@capacitor/cli": "^3.3.3",

Please advice.

**Comment by ntkzwane** [comment]
Is there a fix or known workaround for this? I'm still experiencing it on my end
