### ISSUE TITLE
Error in getIdToken

### ISSUE THREAD

**Issue by davisbra** [chemerisuk/cordova-plugin-firebase-authentication#13]
Hi , when I use cordova.plugins.firebase.auth.getIdToken().then(function(id){})  method "Uncaught (in promise) JSON error" this error returned.
how can I resolve it?

**Comment by evertonrobertoauler** [comment]
Issue fixed in this Pull Request:

https://github.com/chemerisuk/cordova-plugin-firebase-authentication/pull/19

**Comment by chemerisuk** [comment]
Fix published in v0.13.2

**Comment by innoflash** [comment]
Hi @davisbra , getting this error means you have gone as far as i wish to. Do you mind helping me with info on this 
![1](https://user-images.githubusercontent.com/12772919/51730306-a6a0c400-207f-11e9-8cc1-c26c24d61c50.png)

I literally have no idea where i am gonna get the parameters specificied and reading the docs at official firebase seems a mystery to me. 

Can you please direct me to where i can pull these ones out, 

Thanks in advance
