### ISSUE TITLE
This app is not authorized to use Firebase Authentication

### ISSUE THREAD

**Issue by alextapia007** [chemerisuk/cordova-plugin-firebase-authentication#15]
the message is: Please verifythat the correct package name and SHA-1 are configured in the Firebase Console.

i already did...

**Comment by felaray** [comment]
same,how fix it?

**Comment by alextapia007** [comment]
check if SHA-1 is release or debug, i include both in the project.

**Comment by Manidos** [comment]
> same,how fix it?

You need to generate SHA-1 fingerprint using [this](https://stackoverflow.com/a/29421140/5663381)
Then add the fingerprint to firebase console
