### ISSUE TITLE
No register with email and Password function what should we do

### ISSUE THREAD

**Issue by NicOfNoomers** [chemerisuk/cordova-plugin-firebase-authentication#16]
I am looking for a function that will register the user with email and password. Is there a possible way to do that with java and implement it into this plugin! And can you make a tutorial on how to make the plugin work? How do we set it up?

**Comment by chemerisuk** [comment]
Use https://github.com/chemerisuk/cordova-plugin-firebase-authentication#createuserwithemailandpasswordemail-password in the latest version
