### ISSUE TITLE
how to get the idToken and accessToken for Google sign-in?

### ISSUE THREAD

**Issue by Zvika88** [chemerisuk/cordova-plugin-firebase-authentication#17]
trying to implement the plugin for google sign in.	Your text refers to the Firebase docs but they dont seem to refer to such tokens.  The reference to android  doc only mentions a  server token and the reference to iOS doc mention other things (twitter stuff). Can you please provide more specific instructions for the tokens needed for Google sign in?

Thanks!
Z.

**Comment by chemerisuk** [comment]
You can find it in documentation:
https://firebase.google.com/docs/auth/android/google-signin
https://firebase.google.com/docs/auth/ios/google-signin

**Comment by ThonyFD** [comment]
for those how are staring with this, use this method to get the id Token:

`firebase.auth.GoogleAuthProvider();`

**Comment by innoflash** [comment]
@Zvika88  have you found the easiest way of getting those values?

**Comment by ChinchillaReactor** [comment]
this is too complicated.
they say id client... the others say web client id...  idtoken is a firebase ID.

Connecting this APIs is hell.

There is any 10 pages smart tutorial for this?

**Comment by ThonyFD** [comment]
@ChinchillaReactor I have it done, this is the way:

1. If you ar using ionic install @ionic-native/google-plus
2. Call Google Plus login like this:

`const googleResp: GoogleInfoModel = await this.googlePlus.login({
        'scopes': '',
        'webClientId': environment.googleWebClientId,
        'offline': true
      });`

3. Call Firebase Authentication signInWithGoogle method like this: 

`const fireAuth: GoogleInfoModel = await this.firebaseAuthentication.signInWithGoogle(googleResp.idToken, googleResp.accessToken);`

That's all, I'm using my own GoogleInfoModel, and async await for better readability.

**My project setting:** 

Ionic:

   ionic (Ionic CLI)  : 4.10.2 (/usr/local/lib/node_modules/ionic)
   Ionic Framework    : ionic-angular 3.9.3
   @ionic/app-scripts : 3.2.3

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : android 7.1.4, browser 5.0.4
   Cordova Plugins       : cordova-plugin-ionic 5.3.0, cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 3.1.2, (and 12 other plugins)

System:

   ios-deploy : 1.9.4
   NodeJS     : v11.0.0 (/usr/local/bin/node)
   npm        : 6.9.0
   OS         : macOS Mojave
   Xcode      : Xcode 10.1 Build version 10B61

**Comment by sinergymedia** [comment]
`  doGoogleLogin(){
     return new Promise<FirebaseUserModel>((resolve, reject) => {
       if (this.platform.is('cordova')) {
         this.googlePlus.login({
           'scopes': '', // optional, space-separated list of scopes, If not included or empty, defaults to `profile` and `email`.
           'webClientId': environment.googleWebClientId, // optional clientId of your Web application from Credentials settings of your project - On Android, this MUST be included to get an idToken. On iOS, it is not required.
           'offline': true
         }).then((response) => {
           const googleCredential = firebase.auth.GoogleAuthProvider.credential(response.idToken);
           firebase.auth().signInWithCredential(googleCredential)
           .then((user) => {
             resolve();
           });
         },(err) => {
           reject(err);
         });
       }
       else{
         this.afAuth.auth
         .signInWithPopup(new firebase.auth.GoogleAuthProvider())
         .then((user) => {
            resolve()
         },(err) => {
          reject(err);
        })
       }
     })
   }
`
