### ISSUE TITLE
social auth status

### ISSUE THREAD

**Issue by ChristoRibeiro** [chemerisuk/cordova-plugin-firebase-authentication#2]
Hi @chemerisuk, do you plan to support social authentication? Google, FB...

**Comment by chemerisuk** [comment]
Currently this is not planned - may be better to create separate plugins

**Comment by christoribeiro** [comment]
on Firebase docs, all authentication (sms, email, google fb...) are in the same section. It could be a good idea to cover all of them in this plugin?

**Comment by chemerisuk** [comment]
@ChristoRibeiro check new methods in 0.13.0
