### ISSUE TITLE
Merge into the "main firebase repo"

### ISSUE THREAD

**Issue by Hirbod** [chemerisuk/cordova-plugin-firebase-authentication#21]
Hi @chemerisuk 

looks like you're the first one who really implemented the native way of authentication. Sadly, this repo lacks of all the other firebase features - probably for a reason. But would you consider to add your awesome verification stuff to https://github.com/arnesson/cordova-plugin-firebase ?

This would be something awesome, as the other menitoned repo has a very hacky workaround for the verification process (and it only supports the phone-verification in combination with the js api and it also does not cover instant-verification).

Im not sure if I should mix both libs.. feels dirty and might lead into issues with firebase versions..

**Comment by chemerisuk** [comment]
Sorry, I do not have time on this task.
