### ISSUE TITLE
question using firestore

### ISSUE THREAD

**Issue by alextapia007** [chemerisuk/cordova-plugin-firebase-authentication#26]
Hi.
Im already login and have my firebase uid, when try tu use firestore (firebase-firestore.js) i cant, because dont detect my uid... are you know some way to solve?

when i use:
cordova.plugins.firebase.auth.onAuthStateChanged bring me back the user info.
but when i use:
firebase.auth().onAuthStateChanged the result is null.

if in firesotre modify the rule to allow all, work fine, but when i just allow when are loged in... dont work.

the rule:
allow read, write: if request.auth.uid != null;

**Comment by alextapia007** [comment]
thanks @douglaszaltron i will try.

**Comment by peterpahaaan** [comment]
Is there an example code somewhere? I'm stuck at this point. Thank you

> @alextapia007
> The plugin does not authenticate the JavaScript user, what you can do is use the token and generate a credential authentication using the Firebase JavaScript SDK.
