### ISSUE TITLE
Cordova 6.5.0: Could not get unknown property 'FIREBASE_AUTH_VERSION' for object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler

### ISSUE THREAD

**Issue by andreszs** [chemerisuk/cordova-plugin-firebase-authentication#29]
I'm creating a PR to solve this issue by removing the `FIREBASE_AUTH_VERSION` parameter and manually setting it to `16.0.+` as this is the only workaround I found. If someone knows how to implement it properly, he or she could create a new PR.

Output from Visual Studio (**cordova 6.5.0 & cordova-android 6.3.0**)

![firebasecli650](https://user-images.githubusercontent.com/10298071/41384915-ec83db3e-6f4e-11e8-93c5-ab9ce6466e08.png)

**Comment by chemerisuk** [comment]
Have you tried to update Cordova CLI?

**Comment by andreszs** [comment]
Upgrading to CLI 7.1.0 makes the plugin work correctly, but introduces problems with certain plugins so I can't simply upgrade it for the moment. README should be updated to reflect what is the minimum CLI and cordova-android, cordova-ios versions required if this PR is rejected.

**Comment by chemerisuk** [comment]
I’m going to update all plugins tomorrow to clarify cli and cordova-android versions.

**Comment by chemerisuk** [comment]
Ended with updating the <engines> tag that now forces cordova-cli >= 7.1 and cordova-android >= 7. The first one should fix issues with variables. Starting with cordova-android 7 minSdk is 19, where only chromium webviews that have Promises. 

For your case - just add a Promise polyfill. And I also recommend to solve issues with plugin imcompatibility and update cli. It could save you a day in future.
