### ISSUE TITLE
Android 4: Promise is not defined

### ISSUE THREAD

**Issue by andreszs** [chemerisuk/cordova-plugin-firebase-authentication#31]
The plugin does not work at all on Android 4.x because it relies on the new ES6 promise model:

![promise](https://user-images.githubusercontent.com/10298071/41434079-0b78de7a-6ff1-11e8-8f01-09b60260b270.png)

Please be aware that even when Google or Apache Cordova deprecates Android 4.x and 5.x there are still **millions** of devices out there using them, and there will be for a long time, specially in developing countries.

**I think that plugins should stay as backwards compatible as possible, instead of relying on new methods, which should be used only when there is absolutely no alternative.**  Callbacks may take longer to develop but they just work.

Promises are completely unnecessary in this plugin and should be avoided like the plague if you want to develop an useful, reliable and popular plugin, otherwise why bother uploading it? The same goes for the **CLI 7.1.0** requirement just because Gradle does not understand the `FIREBASE_AUTH_VERSION` parameter, another irrelevant feature that breaks the plugin.

If you agree, I'll create a PR to get rid of all promises and implement regular callbacks, otherwise I'll start my own Android 4 compatible branch, damaging the plugins ecosystem which is already quite messed up. Regards,
Andres.-

**Comment by chemerisuk** [comment]
https://github.com/chemerisuk/cordova-plugin-firebase-authentication/issues/29#issuecomment-397753763

**Comment by andreszs** [comment]
I've created a PR to add the required dependency [cordova-promise-polyfill](https://github.com/rehy/cordova-promise-polyfill) and fix this issue, tested it successfully on devices and emulators.

**Comment by chemerisuk** [comment]
This is only relevant for old Android and iOS web views, so is not going to be merged into master. Please keep it in your fork.
