### ISSUE TITLE
Revert to cordova-android 6.3.0

### ISSUE THREAD

**Issue by andreszs** [chemerisuk/cordova-plugin-firebase-authentication#33]
Asking for cordova-android 7 creates several problems like a total incompatibility with Android 4, and failure to develop and deploy with Visual Studio. Creating PR to revert it to 6.3.0, it works perfectly fine with CLI 7.1.0 and on Android 4 using the polyfill for your Promise methods.

**Comment by chemerisuk** [comment]
Old cordova has weird quirks, not going to be merged sorry
