### ISSUE TITLE
VerifyPhoneNumber

### ISSUE THREAD

**Issue by hongnk** [chemerisuk/cordova-plugin-firebase-authentication#4]
When call verifyPhoneNumber from javascript, if phone is auto verified no sms is sent, on native side it seems onVerificationCompleted is called but no callback is passed to javascript side. How to handle this situation?

**Comment by chemerisuk** [comment]
Let me know if it works for you in v0.12.1

**Comment by hongnk** [comment]
I still face this error:

Terminating app due to uncaught exception
'NSInternalInconsistencyException', reason: 'The default FIRApp instance
must be configured before the default FIRAuthinstance can be initialized.
One way to ensure that is to call `[FIRApp configure];`
(`FirebaseApp.configure()` in Swift) in the App Delegate's
`application:didFinishLaunchingWithOptions:`
(`application(_:didFinishLaunchingWithOptions:)` in Swift).'
*** First throw call stack:

at line [[FIRPhoneAuthProvider provider] verifyPhoneNumber:phoneNumber

I have GoogleService-Info.plist copied in platforms/ios/APpName  as well as
inside app Resources folder. That setting file is working fine with
https://github.com/arnesson/cordova-plugin-firebase however somehow this
plugin generates  something in iOS that makes my phone number blocked
immediately by firebase after just a few test attempts due to suspected
activity.

Your plugin works well on android though, no blocking. Therefore I am
hoping that it works on iOS too.

Thanks
Hong
