### ISSUE TITLE
Get emailVerified.

### ISSUE THREAD

**Issue by DarioSam81** [chemerisuk/cordova-plugin-firebase-authentication#44]
hi,
i have a cordova project in JS.
I can read userinfo properties but not user properties. I need lock authentication if email is not verified: how can i do?
Thanks.

**Comment by rssh22** [comment]
Hi, any news on this question? I have the same question than DarioSam81

**Comment by chemerisuk** [comment]
@DarioSam81 @rssh22 Please let me know if v1.1.0 works for you.
