### ISSUE TITLE
Do verifyPhoneNumber needs a reCAPTCHA ?

### ISSUE THREAD

**Issue by achillelrc** [chemerisuk/cordova-plugin-firebase-authentication#46]
Hi,
On Ionic I cannot use the native firebase plugin because it needs a reCAPTACHA and on Ionic's apps this method cannot work.
Great exemple of the issue here : https://javebratt.com/firebase-phone-authentication/
Thanks 
Achille

**Comment by andreszs** [comment]
**Ionic** is build on top of **Cordova**, and the reCAPTCHA implementation works perfectly fine with Cordova 7 and 8 on both Android and iOS. This issue should be reported in the Ionic bugs board, not here.
