### ISSUE TITLE
Ionic 3 

### ISSUE THREAD

**Issue by Lesruez93** [chemerisuk/cordova-plugin-firebase-authentication#47]
Can I use This plugin in my Ionic App Please Help

**Comment by Lordonnance** [comment]
Hello @Lesruez93 did you manage to implement the plugin in an Ionic 3/4 app ? We are struggling at Firebase phone auth with Ionic.

Thanks

**Comment by IngAjVillalon** [comment]
I just made it work fine with no problem in Ionic 5. 
My application runs very well with the login with Phone, Google, and Facebook.
It worked fine with Capacitor (v2) and Cordova (v9).
