### ISSUE TITLE
Firebase configure xcode runtime error

### ISSUE THREAD

**Issue by hongnk** [chemerisuk/cordova-plugin-firebase-authentication#5]
Error: 
The default FIRApp instance must be configured before the default FIRAuthinstance can be initialized. One way to ensure that is to call `[FIRApp configure];` (`FirebaseApp.configure()

How to do that?

**Comment by shunmugarajrntbci** [comment]
??? how to configure in cordova

**Comment by chemerisuk** [comment]
Published 0.14.0
