### ISSUE TITLE
Can't sign in with firebase / GoogleAuthProvider

### ISSUE THREAD

**Issue by rssh22** [chemerisuk/cordova-plugin-firebase-authentication#50]
I've followed the instructions from https://firebase.google.com/docs/auth/web/cordova and I'm having the next issue:

After the this.afAuth.auth.signInWithRedirect(provider) the app redirect to google chrome to the firebase service from google. Then the service return back to a http://localhost:8080/login which is denied by my app with a ERR_CONNECTION_REFUSED.

This is my angular component:

`import { Component, OnInit } from '@angular/core';
import { AngularFireAuth } from '@angular/fire/auth';
import { auth } from 'firebase/app';

@Component({
  selector: 'app-login',
  templateUrl: './login.page.html',
  styleUrls: ['./login.page.scss'],
})
export class LoginPage implements OnInit {

  username: string ="";
  password: string ="";
  kk: string = "";
  constructor(public afAuth: AngularFireAuth) { }

  ngOnInit() {
    this.kk = "hola";
  }

  
  async login() {
    const {username, password} = this;
    try {
      const res = await this.afAuth.auth.signInWithEmailAndPassword(username + '@codedamn.com', password)
    } catch(err) {
      console.dir(err)
      if (err.code === "auth/user-not-found") {
        console.log("User not found");
      }
    }
   }

   async login2() {
    var provider = new auth.GoogleAuthProvider();
    await this.afAuth.auth.signInWithRedirect(provider).then(function() {
      return this.afAuth.auth.auth().getRedirectResult();
    }).then(function(result) {
      // This gives you a Google Access Token.
      // You can use it to access the Google API.
      var token = result.credential.accessToken;
      // The signed-in user info.
      var user = result.user;
      // ...
    }).catch(function(error) {
      // Handle Errors here.
      var errorCode = error.code;
      var errorMessage = error.message;
    });
  
   }

}`

**Comment by rssh22** [comment]
More info:

PS C:\Users\raul\ionic\app> ionic info

Ionic:

   ionic (Ionic CLI)             : 4.6.0 (C:\Users\raul\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 4.0.0-rc.0
   @angular-devkit/build-angular : 0.11.4
   @angular-devkit/schematics    : 7.1.4
   @angular/cli                  : 7.1.4
   @ionic/angular-toolkit        : 1.2.2

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : android 7.1.4, browser 5.0.4
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 2.3.1, (and 4 other plugins)

System:

   NodeJS : v11.4.0 (C:\Program Files\nodejs\node.exe)
   npm    : 6.4.1
   OS     : Windows 10

**Comment by chemerisuk** [comment]
This plugin does not relies on https://firebase.google.com/docs/auth/web/cordova
