### ISSUE TITLE
Error with signInWithVerificationId parameter mismatch

### ISSUE THREAD

**Issue by jmoren** [chemerisuk/cordova-plugin-firebase-authentication#53]
I am getting an error sending the verificationId and SMSCode:

```
by.chemerisuk.cordova.firebase.FirebaseAuthenticationPlugin.signInWithVerificationId argument 2 has type java.lang.String, got java.lang.Integer
```
this.firebaseAuthentication.signInWithVerificationId(this.verificationId, Number(code)) expects a number in the code parameter, but actually expects a string parameter.

Package json:
```
"cordova-plugin-firebase": "2.0.5",
"cordova-plugin-firebase-authentication": "1.0.1",
```
    
Cordova plugins:
```
"cordova-plugin-firebase": {},
"cordova-plugin-firebase-authentication": {
   "FIREBASE_AUTH_VERSION": "16.1.0"
}
```

**Comment by jmoren** [comment]
@chemerisuk I am doing something wrong?

```this.firebaseAuthentication.signInWithVerificationId(this.verificationId, Number(code))```

beacuse 

```this.firebaseAuthentication.signInWithVerificationId(this.verificationId, code)```

is saying `Argument of type 'string' is not assignable to parameter of type 'number'.ts(2345)`

**Comment by chemerisuk** [comment]
You don't need Number(code), just code as a string should work.

**Comment by jmoren** [comment]
Well, actually that is the problem. If I put code as string, I got an error. If I put the code as Number, I got another error.
`this.firebaseAuthentication.signInWithVerificationId(this.verificationId, Number(code))` Error with java
`this.firebaseAuthentication.signInWithVerificationId(this.verificationId, code)` Error compiling.

**Comment by chemerisuk** [comment]
I looked at the source. Parameter `code` expected everywhere to be a string, not a number.

**Comment by jmoren** [comment]
To make it work, I should change this line in the file:
`node_modules/@ionic-native/firebase-authentication/index.d.ts#70`
smsCode: Number -> smsCode: String
```
/**
* Asynchronously signs in using verificationId and 6-digit SMS code.
* @param verificationId Verification ID
* @param smsCode SMS code
*/
signInWithVerificationId(verificationId: string, smsCode: string): Promise<any>;
```
and this file
`node_modules/@ionic-native/firebase-authentication/index.js#352`
__metadata("design:paramtypes", [String, Number]), -> __metadata("design:paramtypes", [String, String]),
```
__decorate([
    Cordova({ sync: true }),
    __metadata("design:type", Function),
    __metadata("design:paramtypes", [String, String]),
    __metadata("design:returntype", Promise)
], FirebaseAuthentication.prototype, "signInWithVerificationId", null);
```
Was the only way to make it work...
Thanks.

**Comment by chemerisuk** [comment]
Open issue at the ionic plugin repo, the bug there.
