### ISSUE TITLE
Error installing the plugin

### ISSUE THREAD

**Issue by premtemp1** [chemerisuk/cordova-plugin-firebase-authentication#55]
Hello,
  Getting error installing the plugin...

Please let me know how to resolve

Thanks

cordova plugin add cordova-plugin-firebase-authentication --save
Installing "cordova-plugin-firebase-authentication" for android
Plugin dependency "cordova-support-android-plugin@1.0.1" already fetched, using that version.
Installing "cordova-support-android-plugin" for android
Android Studio project detected
Plugin dependency "cordova-support-google-services@1.3.1" already fetched, using that version.
Installing "cordova-support-google-services" for android
Subproject Path: CordovaLib
Subproject Path: app
Subproject Path: CordovaLib
Subproject Path: app
Installing "cordova-plugin-firebase-authentication" for browser
Installing "cordova-plugin-firebase-authentication" for ios
Failed to install 'cordova-plugin-firebase-authentication': Error: pod: Command failed with exit code 31
    at ChildProcess.whenDone (/Users/Documents/testing/fb/MobileV2/platforms/ios/cordova/node_modules/cordova-common/src/superspawn.js:169:23)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
pod: Command failed with exit code 31

**Comment by chemerisuk** [comment]
Something wrong with your cocopods dependencies.
