### ISSUE TITLE
How to write firebase database rules with this plugin

### ISSUE THREAD

**Issue by nemchand123** [chemerisuk/cordova-plugin-firebase-authentication#60]
Hello,
thanks for the great plugins,

I used "signInWithVerificationId()" in my ionic Application. Every thing is working great. **But i am not able to use Firebase database rules with this plugin. Below are my codes. Please help to implement database rules.**

I used [https://ionicframework.com/docs/v3/native/firebase-authentication/](url) to authenticate users
and [https://www.npmjs.com/package/firebase](url) to access firebase data.

### **Function to send OTP**
`  send(){
    this.firebaseAuthentication.verifyPhoneNumber(this.mobile,60).then((data)=>{
      console.log(data)
      this.verificationId = data;
      alert('OTP SENT');
    },error=>{
      console.log(error)
    })
  }`

### **Code to login**
`  verify(){
    this.firebaseAuthentication.signInWithVerificationId(this.verificationId, this.code).then((verified)=>{
      if(verified=='OK'){
        console.log('user loggedin successfully')
      }
    },error=>{
      console.log(error)
    })
  }`

### **Code to fetch data**
`      this.firebaseAuthentication.onAuthStateChanged().subscribe((user)=>{
        if(user){
          console.log(user);
          firebase.database().ref('dummydata').on('value',snapshot=>{
            console.log('data ',snapshot.val())
          },error=>{
            console.log('error ',error)
          })
        }`

### **Database rule**
`{
  "rules": {
    "dummydata":{
       	".read": "auth!=null",
    		".write": "auth!=null"
    }
  }
}`

**Comment by uzbekjon** [comment]
Firebase security rules have nothing to do with this plugin. You can read and lear more about them in their [docs](https://firebase.google.com/docs/rules), specific rules related to realtime database [doc](https://firebase.google.com/docs/database/security) or here is a [video intro](https://www.youtube.com/watch?v=PUBnlbjZFAI).

In your code above, it seems like you are allowing to read and write to authenticated users only. For testing only, you may allow read and write to anyone like this:

```json
{
  "rules": {
    "foo": {
      ".read": true,
      ".write": false
    }
  }
}
```

And when the time comes to deploy, you obviously want to define these rules according to your business rules.
