### ISSUE TITLE
where to put my firebase credentials ?

### ISSUE THREAD

**Issue by sumit-youngdecade** [chemerisuk/cordova-plugin-firebase-authentication#61]
Hi in the documentation there is no clue where to put firebase credentials and is this plugin will work on IOS and android???

**Comment by uzbekjon** [comment]
> is this plugin will work on IOS and android???

The plugin supports iOS and Android.

> where to put firebase credentials

Go to Firebase console and add iOS or Android application. You will be presented with the wizard to download your configuration file. More detailed explanation on how to do it here [iOS](https://firebase.google.com/docs/ios/setup)/[Android](https://firebase.google.com/docs/android/setup). For example, for Android app, you will have to put your `google-services.json` file into the `platforms/android/app` folder.
