### ISSUE TITLE
verifyPhoneNumber is not sendig sms code ?

### ISSUE THREAD

**Issue by RANJITSIKKA** [chemerisuk/cordova-plugin-firebase-authentication#63]
cordova.plugins.firebase.auth.verifyPhoneNumber("+91+number", 30000).then(function(verificationId) {
            // pass verificationId to signInWithVerificationId
            alert(verificationId);
     });
        alert("done");

**Comment by binarybehemoth** [comment]
hey....I am facing the same problem. Did you manage to solve the problem?
