### ISSUE TITLE
Where can I get an idToken for google login to firebase?

### ISSUE THREAD

**Issue by martijnmichel** [chemerisuk/cordova-plugin-firebase-authentication#72]
I don't see anything about an idToken in the links under the method :(

**Comment by chemerisuk** [comment]
https://firebase.google.com/docs/auth/android/google-signin
https://firebase.google.com/docs/auth/ios/google-signin

**Comment by sanket-webmavens** [comment]
In those links, there's a bunch of code written in java, which is quite confusing. My current project in AngularJs, your help is appreciated. Thanks

**Comment by jessk77** [comment]
We are using a plugin for an app in js not in java or kotlin, has somebody find an answer? Thanks
