### ISSUE TITLE
FirebaseAuthenticationPlugin.h iOS | Firebase module not found

### ISSUE THREAD

**Issue by haseebazeem15** [chemerisuk/cordova-plugin-firebase-authentication#73]
![Screen Shot 2019-11-15 at 8 21 54 AM](https://user-images.githubusercontent.com/39488408/68914643-1011d080-0781-11ea-807b-c9ced014e3f3.png)

I have tried pod install but the still the same issue. How to resolve it?

**Comment by moblizeit** [comment]
i am facing the same plz advise

**Comment by hamzahalvanaa** [comment]
i have solved the issue by doing `npm install -S firebase@canary`
