### ISSUE TITLE
Support for Sign in with Apple

### ISSUE THREAD

**Issue by akadebnath** [chemerisuk/cordova-plugin-firebase-authentication#74]
iOS apps that offer third party sign in (Sign in with Google/Facebook etc) now requires to include Sign in with Apple feature. Firebase recently added the feature, as per the below blog post:

https://firebase.googleblog.com/2019/11/sign-in-with-apple-auth.html

And this discussion:

https://github.com/firebase/firebase-ios-sdk/issues/3145

Any idea when this cordova plugin can be updated to include the feature.

Thank you.

**Comment by vandres** [comment]
Yes, please

**Comment by amirhmoradi** [comment]
Hi @chemerisuk , thanks for all your great cordova plugins! We use many of them in our apps.

Could you let us know when will you be able to implement signin with apple feature so that we may provide this feature to our customers?

Best

**Comment by imranaalam** [comment]
please share phoneauth specifics? most of us are stuck at that part of silent APM.

**Comment by havo07** [comment]
Has anyone already logged in with Apple?

**Comment by svzi** [comment]
@chemerisuk Any update on this topic? Do you plan to implement the requested functionality? It's already available here: https://github.com/dpa99c/cordova-plugin-firebasex

Maybe you can incorporate the changes made by Dave into this plugin?

**Comment by chemerisuk** [comment]
@svzi @akadebnath @vandres @amirhmoradi In my app that is currently used for testing I do not need sign in with Apple. Therefore feature development is slow. Let me know If you can help with the implementation/testing or sponsor the process.

**Comment by svzi** [comment]
@chemerisuk Could you please drop me an e-mail? You'll find it in my profile (i was unable to find yours).

**Comment by chemerisuk** [comment]
@svzi feel free to write your thoughts here, so other people in the topic can respond too.

**Comment by svzi** [comment]
@chemerisuk I just wanted to talk about the ability on how to sponsor the process. What is your pricing tag to implement this feature?

**Comment by chemerisuk** [comment]
@svzi please check our email.

**Comment by chemerisuk** [comment]
Published in v3.5.0, read [instructions](https://github.com/chemerisuk/cordova-plugin-firebase-authentication#signinwithappleidtoken-rawnonce).

**Comment by akadebnath** [comment]
Thank you a lot for including the feature. I believe we all the users can send a coffee to you for keeping the great plugin great. Unfortunately, PayPal donation is not supported in my country. You can let us know any other way around.
