### ISSUE TITLE
Convert cordova-plugin-firebase-authentication auth user to Firebase JS-SDK auth.

### ISSUE THREAD

**Issue by bhar4t** [chemerisuk/cordova-plugin-firebase-authentication#75]
I am using mobile verification authentication by cordova plugin cordova-plugin-firebase-authentication. The plugin is working fine, I can login, logout everything, which this defined in their documentation.

With this plugin I am using Firebase JS-SDK for firestore, As I am using third party authentication mechanism the firebase defined onAuthStateChanged is not working and it is obvious, and because of this onAuthStateChanged gives null for auth user.

I want to convert cordova-plugin-firebase-authentication auth user to firebase js-sdk auth user, or how can I use cordova-plugin-firebase-authentication auth user request.auth.uid in firebase security rules.

https://stackoverflow.com/questions/59208960/convert-cordova-plugin-firebase-authentication-auth-to-firebase-js-sdk-auth

**Comment by chemerisuk** [comment]
Read docs, issues here is for bug reports.
