### ISSUE TITLE
Apple warning about deprecated UIWebView api

### ISSUE THREAD

**Issue by hoangDung096** [chemerisuk/cordova-plugin-firebase-authentication#81]
I uploaded the build file into the testflight. After that i received this apple warning: "TMS-90809: Deprecated API Usage - Apple will stop accepting submissions of apps that use UIWebView APIs . See https://developer.apple.com/documentation/uikit/uiwebview for more information."

I tried remove this plugin. Then i haven't received this warning anymore. So the problem from this plugin. It had UIWebView code.

**Comment by chemerisuk** [comment]
It doesn't
```
$ pod repo update
```
