### ISSUE TITLE
plugin not installed on ios platform

### ISSUE THREAD

**Issue by AakashJadav** [chemerisuk/cordova-plugin-firebase-authentication#90]
plugin not installed ios platform and the entry only shows in package.json file not in config.xml. this plugin skipping to install it on ios platform if your cordova cli version is 8.0.0 so i upgrade it to 9.0.0 but now it does not install on ios platform. Any solution for this? Thanks in advance.

ionic info as below.

Ionic:

   Ionic CLI          : 6.2.1 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework    : ionic-angular 3.9.5
   @ionic/app-scripts : 3.2.2

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : none
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.1.1, (and 13 other plugins)

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v12.16.1 (/usr/local/bin/node)
   npm    : 6.14.2
   OS     : macOS Catalina
   Xcode  : Xcode 11.1 Build version 11A1027

**Comment by chemerisuk** [comment]
@AakashJadav read your cli log.
