### ISSUE TITLE
App is not authorized to use Firebase Auth

### ISSUE THREAD

**Issue by hamzahalvanaa** [chemerisuk/cordova-plugin-firebase-authentication#92]
Hi @chemerisuk , thanks for creating an awesome plugin. Recently I've set up my firebase console then installed the plugin (and ionic native plugin) as well.

But it says error "**This app is not authorized to use Firebase Authentication. Please verify that the correct package name and SHA-1 are configured in the Firebase Console. [ App validation failed ]**" when using verifyPhoneNumber method.

Let me know what the possible way to solve this problem? Thank you.

**Comment by chemerisuk** [comment]
Read docs: https://firebase.google.com/docs/auth/android/phone-auth#before-you-begin
