### ISSUE TITLE
unable to install on ios for ionic

### ISSUE THREAD

**Issue by moblizeit** [chemerisuk/cordova-plugin-firebase-authentication#98]
moblizeit@MacBook-Pro-5 doodles % ionic info

Ionic:

   Ionic CLI                     : 6.9.1 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.1.0
   @angular-devkit/build-angular : 0.803.26
   @angular-devkit/schematics    : 8.3.26
   @angular/cli                  : 8.3.26
   @ionic/angular-toolkit        : 2.2.0

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.1.0, browser 6.0.0, ios 5.1.1
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.2.1, (and 18 other plugins)

Utility:

   cordova-res (update available: 0.14.0) : 0.8.1
   native-run (update available: 1.0.0)   : 0.2.9

System:

   ios-deploy : 1.9.4
   ios-sim    : 8.0.2
   NodeJS     : v10.14.1 (/usr/local/bin/node)
   npm        : 6.14.5
   OS         : macOS Catalina
   Xcode      : Xcode 11.2.1 Build version 11B53

If i do on cli ionic cordova build ios  it fails with below error:
The following build commands failed:
	CompileC /Users/moblizeit/Library/Developer/Xcode/DerivedData/Doodles-adkdivmzenbpjfarkekytdxgoobk/Build/Intermediates.noindex/Doodles.build/Debug-iphonesimulator/Doodles.build/Objects-normal/x86_64/FirebaseAuthenticationPlugin.o /Users/moblizeit/code-repo/doodles/doodles/platforms/ios/Doodles/Plugins/cordova-plugin-firebase-authentication/FirebaseAuthenticationPlugin.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
xcodebuild: Command failed with exit code 65
[ERROR] An error occurred while running subprocess cordova.
        
        cordova build ios exited with exit code 65.

If i open the .workspace file in Xcode and build it shows error:
module 'Firebase' not found  'FirebaseAuthenticationPlugin.h'

I have tried everything but no luck. on android all works fine.

**Comment by imranaalam** [comment]
Have you solved the issue; i am facing the same problem.

**Comment by Kohlibrie** [comment]
Do you have some tips for this issue?
